### ISSUE TITLE
Migrate data input screen to coa_ui

### ISSUE THREAD

**Issue by mcampellone10** [CleanOceanAction/coa_app#11]
Migrate the data input screen on coa_app to coa_ui to reduce need to keep both web apps running.

**Comment by mwilli20** [comment]
I started working on the backend migration from the old coa_app to the coa_flask_app. Will probably team up with @jerrylin1218 or @maithuvenkatesh when I get to the point we are looking to make the front end changes.

@mcampellone10 When going through the backend code I saw there is an impact page which we said can go, the contributions page we is the form to migrate over, but I also found a leaderboard. Is that meant to move over as well?

**Comment by mcampellone10** [comment]
@mwilli20 no need to migrate the leaderboard over. that was something we used for a data hackathon to see what employees participating cleaned up the most data when doing the initial COA data scrub.

**Comment by mwilli20** [comment]
@mcampellone10 Ok cool and last one, what about this admin page. It doesn't seem to work, but the idea was to add a screen to add a new site and add a team leader. There was also commented out / on finished code to remove a team leader from the system. Or this page that is up: http://coa-app.elasticbeanstalk.com/contribution/thank_you

**Comment by mcampellone10** [comment]
@mwilli20 can you send a screenshot of the admin page? this we may want to migrate over to be safe

**Comment by mwilli20** [comment]
@mcampellone10 Thats sadly not something I can do, as the page doesn't exist yet. There are a few of these partially done pages where they don't load or anything but you can see these partially done screens were checked in, making me think there was a desire at some point. Not sure if that changed, but honestly it might be better to let them go, and if they want them it will be easier to probably re add them in the future.

**Comment by mwilli20** [comment]
Confirmed at the meeting today. Will be getting followed up on the details #13 instead.

**Comment by mwilli20** [comment]
We will be picking this back up, some details to come.

**Comment by mwilli20** [comment]
This will be happening in coa_ui and replace most things in this repo
