### ISSUE TITLE
COA Github Organization

### ISSUE THREAD

**Issue by kiljomas** [CleanOceanAction/coa_app#4]
Currently, CleanOceanAction is an account, but it might make sense to change this to an organization so we can be members. This will make contributing and maintaining the repo much easier.

**Comment by CleanOceanAction** [comment]
This is a good idea. Let me see if I can change it right now.

**Comment by maithuvenkatesh** [comment]
Done. I've made myself (maithuvenkatesh) owner but this can always be changed. I've also added Priyanka and you as contributors!
